import { useState } from 'react';

export default function DocumentDemo() {
  const [template, setTemplate] = useState('contract');
  const [fields, setFields] = useState({
    company: 'Acme Corp',
    client: 'GlobalTech Inc.',
    date: new Date().toLocaleDateString(),
    amount: '$45,000',
    terms: 'Net 30',
  });

  const templates: Record<string, string> = {
    contract: `SERVICE AGREEMENT

This agreement is made between ${fields.company} ("Provider")
and ${fields.client} ("Client") effective ${fields.date}.

Scope of Work: Provider agrees to deliver software
development services as outlined in Exhibit A.

Payment Terms: Client agrees to pay ${fields.amount}
with payment terms of ${fields.terms}.

This document was generated by DocuFlow and is
legally binding upon e-signature by both parties.`,

    invoice: `INVOICE

From: ${fields.company}
To: ${fields.client}
Date: ${fields.date}

Description: Software development services
Amount Due: ${fields.amount}
Payment Terms: ${fields.terms}

Please remit payment within the specified terms.
Thank you for your business.`,

    nda: `NON-DISCLOSURE AGREEMENT

This NDA is entered into between ${fields.company}
and ${fields.client} effective ${fields.date}.

The parties agree to keep all shared confidential
information strictly private and not disclose it
to any third party without written consent.

Term: 2 years from the date of execution.
Remedy: Injunctive relief and ${fields.amount} damages.`,
  };

  const preview = templates[template] ?? templates.contract;

  return (
    <div className="liquid-glass rounded-2xl p-6 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded-lg bg-[#38bdf8]/15 flex items-center justify-center text-sm">📄</div>
          <div>
            <h3 className="text-sm font-semibold">DocuFlow</h3>
            <div className="text-[10px] text-[var(--color-text-muted)]">Document Automation · Template Editor</div>
          </div>
        </div>
        <div className="flex gap-1.5">
          {['contract', 'invoice', 'nda'].map((t) => (
            <button key={t} onClick={() => setTemplate(t)}
              className={`px-3 py-1.5 rounded-lg text-[10px] font-medium uppercase transition-all cursor-pointer border ${template === t ? 'bg-white/[0.06] border-white/[0.1] text-white' : 'bg-white/[0.01] border-white/[0.04] text-[var(--color-text-muted)] hover:text-white'}`}>{t}</button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="space-y-2.5">
          <p className="text-[10px] text-[var(--color-text-muted)] uppercase tracking-wider">Dynamic Fields</p>
          {Object.entries(fields).map(([key, val]) => (
            <div key={key} className="flex items-center gap-2">
              <span className="text-[10px] text-[var(--color-text-muted)] w-16 capitalize">{key}</span>
              <input value={val} onChange={(e) => setFields({ ...fields, [key]: e.target.value })}
                className="flex-1 bg-white/[0.02] border border-white/[0.04] rounded-lg px-3 py-1.5 text-[11px] text-white outline-none focus:border-[#38bdf8]/30" />
            </div>
          ))}
        </div>

        <div>
          <p className="text-[10px] text-[var(--color-text-muted)] uppercase tracking-wider mb-2">Live Preview</p>
          <div className="bg-white rounded-xl p-5 text-[11px] text-gray-800 leading-relaxed font-mono h-64 overflow-y-auto border border-white/[0.1] whitespace-pre-line shadow-sm">
            {preview}
          </div>
        </div>
      </div>

      <div className="flex gap-2">
        <button className="flex-1 py-2.5 bg-[#4f8fde] text-white rounded-xl text-sm font-medium hover:bg-[#60a5fa] hover:shadow-[0_4px_16px_rgba(96,165,250,0.2)] transition-all cursor-pointer">Generate Document</button>
        <button className="px-4 py-2.5 bg-white/[0.03] border border-white/[0.06] text-[var(--color-text-secondary)] rounded-xl text-sm font-medium hover:text-white hover:border-white/[0.1] transition-all cursor-pointer">✎ Sign</button>
      </div>
    </div>
  );
}
